/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Yair Ariel
 */
public class ExpensePanel extends javax.swing.JPanel {

    /**
     * Creates new form ExpensePanel
     */
    public ExpensePanel() {
        initComponents();
    }

    public ExpensePanel(final Expense expens) {
        initComponents();
        setLabelExpenseIcon(expens.getTransIcon());
        setLabelExpenseDate(TransactionParser.SIMPLE_DATE_FORMAT.format(expens.getTransDate().getTime()));
        setLabelExpenseAmount(Double.toString(expens.getTransAmount()));
        setLabelExpenseDescription(expens.getTransDescription());
        getLabelExpenseIcon().setToolTipText(expens.getTransPaymentMethod());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelExpenseIcon = new javax.swing.JLabel();
        labelExpenseDate = new javax.swing.JLabel();
        labelExpensePaymentMethod = new javax.swing.JLabel();
        labelExpenseDescription = new javax.swing.JLabel();
        labelExpenseAmount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 241, 240));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 1, 12, 1));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(816, 88));
        setMinimumSize(new java.awt.Dimension(816, 88));
        setPreferredSize(new java.awt.Dimension(816, 88));

        labelExpenseIcon.setBorder(null);

        labelExpenseDate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelExpenseDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExpenseDate.setText("01/01/2017");
        labelExpenseDate.setToolTipText("");
        labelExpenseDate.setBorder(null);

        labelExpensePaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelExpensePaymentMethod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelExpensePaymentMethod.setText("העברה בנקאית");
        labelExpensePaymentMethod.setToolTipText("");
        labelExpensePaymentMethod.setBorder(null);

        labelExpenseDescription.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelExpenseDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelExpenseDescription.setText("אבגדהוזחטיכלמנסעפצקרשת");
        labelExpenseDescription.setToolTipText("");
        labelExpenseDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        labelExpenseDescription.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelExpenseAmount.setBackground(new java.awt.Color(255, 241, 240));
        labelExpenseAmount.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelExpenseAmount.setForeground(new java.awt.Color(242, 65, 21));
        labelExpenseAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelExpenseAmount.setText("2134.67");
        labelExpenseAmount.setToolTipText("");
        labelExpenseAmount.setBorder(null);
        labelExpenseAmount.setOpaque(true);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(3, 64));
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 64));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(3, 64));
        jSeparator2.setPreferredSize(new java.awt.Dimension(3, 64));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMaximumSize(new java.awt.Dimension(3, 64));
        jSeparator3.setPreferredSize(new java.awt.Dimension(3, 64));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setMaximumSize(new java.awt.Dimension(3, 64));
        jSeparator4.setPreferredSize(new java.awt.Dimension(3, 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelExpensePaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelExpenseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelExpenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelExpenseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelExpensePaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelExpenseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelExpenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelExpenseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelExpenseAmount;
    private javax.swing.JLabel labelExpenseDate;
    private javax.swing.JLabel labelExpenseDescription;
    private javax.swing.JLabel labelExpenseIcon;
    private javax.swing.JLabel labelExpensePaymentMethod;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabelExpenseAmount() {
        return labelExpenseAmount;
    }

    public void setLabelExpenseAmount(JLabel labelExpenseAmount) {
        this.labelExpenseAmount = labelExpenseAmount;
    }

    public void setLabelExpenseAmount(String expenseAmount) {
        this.getLabelExpenseAmount().setText(expenseAmount);
    }

    public JLabel getLabelExpenseDate() {
        return labelExpenseDate;
    }

    public void setLabelExpenseDate(JLabel labelExpenseDate) {
        this.labelExpenseDate = labelExpenseDate;
    }

    public void setLabelExpenseDate(String expenseDate) {
        this.getLabelExpenseDate().setText(expenseDate);
    }

    public JLabel getLabelExpenseDescription() {
        return labelExpenseDescription;
    }

    public void setLabelExpenseDescription(JLabel labelExpenseDescription) {
        this.labelExpenseDescription = labelExpenseDescription;
    }

    public void setLabelExpenseDescription(String expenseDescription) {
        this.getLabelExpenseDescription().setText(expenseDescription);
    }

    public JLabel getLabelExpenseIcon() {
        return labelExpenseIcon;
    }

    public void setLabelExpenseIcon(JLabel labelExpenseIcon) {
        this.labelExpenseIcon = labelExpenseIcon;
    }

    public void setLabelExpenseIcon(ImageIcon expenseIcon) {
        this.getLabelExpenseIcon().setIcon(expenseIcon);
    }

    public JLabel getLabelExpensePaymentMethod() {
        return labelExpensePaymentMethod;
    }

    public void setLabelExpensePaymentMethod(JLabel labelExpensePaymentMethod) {
        this.labelExpensePaymentMethod = labelExpensePaymentMethod;
    }

    public void setLabelExpensePaymentMethod(String expensePaymentMethod) {
        this.getLabelExpensePaymentMethod().setText(expensePaymentMethod);
    }
}
