/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

import javax.swing.ImageIcon;

/**
 *
 * @author Shlomo Pfeuffer
 */
public class ExpensePanel extends javax.swing.JPanel {

    /**
     * Creates new form TransactionPanel
     */
    public ExpensePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        catagory = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        method = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 64));
        setMinimumSize(new java.awt.Dimension(800, 64));
        setPreferredSize(new java.awt.Dimension(800, 84));

        icon.setText("icon");

        date.setFont(date.getFont().deriveFont((float)24));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("01/01/2017");
        date.setToolTipText("");
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catagory.setFont(catagory.getFont().deriveFont((float)24));
        catagory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catagory.setText("רכב");
        catagory.setToolTipText("");
        catagory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        amount.setFont(amount.getFont().deriveFont((float)24));
        amount.setForeground(new java.awt.Color(255, 0, 0));
        amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amount.setText("2134.67");
        amount.setToolTipText("");
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        method.setFont(method.getFont().deriveFont((float)24));
        method.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        method.setText("אשראי");
        method.setToolTipText("");
        method.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catagory, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(method, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(catagory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amount)
                    .addComponent(method, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel catagory;
    private javax.swing.JLabel date;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel method;
    // End of variables declaration//GEN-END:variables

    public void setAmountText(String text) {
        this.amount.setText(text);
    }

    public void setCatagoryText(String text) {
        this.catagory.setText(text);
    }

    public void setDateText(String text) {
        this.date.setText(text);
    }

    public void setMethodText(String text) {
        this.method.setText(text);
    }

    public void setIcon(ImageIcon icon) {
        this.icon.setIcon(icon);
    }

}
