/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

/**
 *
 * @author Yair Ariel
 */
public class ExpensePanel extends javax.swing.JPanel {

    /**
     * Creates new form ExpensePanel
     */
    public ExpensePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expensePanelIcon = new javax.swing.JLabel();
        expensePanelDate = new javax.swing.JLabel();
        expensePanelPaymentMethod = new javax.swing.JLabel();
        expensePanelDescription = new javax.swing.JLabel();
        expensePanelAmount = new javax.swing.JLabel();

        expensePanelIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        expensePanelDate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        expensePanelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        expensePanelDate.setText("01/01/2017");
        expensePanelDate.setToolTipText("");
        expensePanelDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        expensePanelPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        expensePanelPaymentMethod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expensePanelPaymentMethod.setText("העברה בנקאית");
        expensePanelPaymentMethod.setToolTipText("");
        expensePanelPaymentMethod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        expensePanelDescription.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        expensePanelDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expensePanelDescription.setText("אבגדהוזחטיכלמנסעפצקרשת");
        expensePanelDescription.setToolTipText("");
        expensePanelDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        expensePanelDescription.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        expensePanelAmount.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        expensePanelAmount.setForeground(new java.awt.Color(242, 65, 21));
        expensePanelAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expensePanelAmount.setText("2134.67");
        expensePanelAmount.setToolTipText("");
        expensePanelAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 65, 21), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(expensePanelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensePanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensePanelPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensePanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensePanelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(expensePanelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expensePanelDate)
                    .addComponent(expensePanelPaymentMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expensePanelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expensePanelAmount))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel expensePanelAmount;
    private javax.swing.JLabel expensePanelDate;
    private javax.swing.JLabel expensePanelDescription;
    private javax.swing.JLabel expensePanelIcon;
    private javax.swing.JLabel expensePanelPaymentMethod;
    // End of variables declaration//GEN-END:variables
}
