/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

/**
 *
 * @author Yair Ariel
 */
public class IncomePanel extends javax.swing.JPanel {

    /**
     * Creates new form IncomePanel
     */
    public IncomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incomePanelIcon = new javax.swing.JLabel();
        incomePanelDate = new javax.swing.JLabel();
        incomePanelPaymentMethod = new javax.swing.JLabel();
        incomePanelDescription = new javax.swing.JLabel();
        incomePanelAmount = new javax.swing.JLabel();

        setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        incomePanelIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        incomePanelDate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        incomePanelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomePanelDate.setText("01/01/2017");
        incomePanelDate.setToolTipText("");
        incomePanelDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        incomePanelPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        incomePanelPaymentMethod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        incomePanelPaymentMethod.setText("העברה בנקאית");
        incomePanelPaymentMethod.setToolTipText("");
        incomePanelPaymentMethod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        incomePanelDescription.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        incomePanelDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        incomePanelDescription.setText("אבגדהוזחטיכלמנסעפצקרשת");
        incomePanelDescription.setToolTipText("");
        incomePanelDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        incomePanelDescription.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        incomePanelAmount.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        incomePanelAmount.setForeground(new java.awt.Color(34, 206, 26));
        incomePanelAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        incomePanelAmount.setText("2134.67");
        incomePanelAmount.setToolTipText("");
        incomePanelAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 206, 26), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(incomePanelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomePanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomePanelPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomePanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomePanelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(incomePanelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomePanelDate)
                    .addComponent(incomePanelPaymentMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(incomePanelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(incomePanelAmount))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel incomePanelAmount;
    private javax.swing.JLabel incomePanelDate;
    private javax.swing.JLabel incomePanelDescription;
    private javax.swing.JLabel incomePanelIcon;
    private javax.swing.JLabel incomePanelPaymentMethod;
    // End of variables declaration//GEN-END:variables
}
