/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import org.jdesktop.swingx.JXDatePicker;
import javax.swing.SpinnerNumberModel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Yair Ariel
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("images/logoIcon.png")).getImage());
        setLocationRelativeTo(null);
        Locale hebrew = new Locale("iw", "IL");
        ComponentOrientation hebrewOri1entation = ComponentOrientation.getOrientation(hebrew);
        jTabbedPaneMenu.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        // General view components
        ((JLabel) comboBoxDatesRange.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);

        // Transactions components
        datePickerFromDate.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        datePickerToDate.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        comboBoxTransactionsData.applyComponentOrientation(hebrewOri1entation);
        ((JLabel) comboBoxTransactionsData.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);

        // Budget components
        spinnerBudgetAmount.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        spinnerAlertBefore.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        CheckBoxHandler cbHandler = new CheckBoxHandler();
        checkBoxAlertBeforeX.addItemListener(cbHandler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelTitleGeneralView = new javax.swing.JLabel();
        buttonNewIncome = new javax.swing.JButton();
        generalViewPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        labelUsedBudget = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelOfBudget = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        progressBarBudget = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelIncomeAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelExpenseAmount = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTransactionSum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxDatesRange = new javax.swing.JComboBox<>();
        buttonNewExpense = new javax.swing.JButton();
        labelTitleTransactions = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelTransactions = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        buttonNewExpense1 = new javax.swing.JButton();
        datePickerToDate = new org.jdesktop.swingx.JXDatePicker(new Date(130,11,30));
        comboBoxTransactionsData = new javax.swing.JComboBox<>();
        buttonNewIncome1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        datePickerFromDate = new org.jdesktop.swingx.JXDatePicker(new Date(110,0,1));
        jLabel13 = new javax.swing.JLabel();
        scrollbarTransactions = new javax.swing.JScrollPane();
        panelScrollInnerContainer = new javax.swing.JPanel();
        panelTransactions = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelTitleBudget = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        labelBudgetTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkBoxAlertBeforeException = new javax.swing.JCheckBox();
        checkBoxEnableEdit = new javax.swing.JCheckBox();
        spinnerAlertBefore = new javax.swing.JSpinner(new SpinnerNumberModel(0.00,0.00,99999999.99,0.01));
        spinnerBudgetAmount = new javax.swing.JSpinner(new SpinnerNumberModel(0.00,0.00,99999999.99,0.01));
        jLabel17 = new javax.swing.JLabel();
        labelSetBudgetSum = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        buttonDefineBudget = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        checkBoxAlertBeforeX = new javax.swing.JCheckBox();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashew - Main Menu");
        setBackground(new java.awt.Color(242, 239, 239));

        jTabbedPaneMenu.setBackground(new java.awt.Color(251, 248, 255));
        jTabbedPaneMenu.setForeground(new java.awt.Color(85, 96, 128));
        jTabbedPaneMenu.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jTabbedPaneMenu.setMinimumSize(new java.awt.Dimension(1200, 652));
        jTabbedPaneMenu.setName(""); // NOI18N
        jTabbedPaneMenu.setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(242, 241, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setBackground(new java.awt.Color(242, 241, 255));

        jPanel3.setBackground(new java.awt.Color(242, 241, 255));

        labelTitleGeneralView.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelTitleGeneralView.setForeground(new java.awt.Color(85, 96, 128));
        labelTitleGeneralView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleGeneralView.setText("מבט על");
        labelTitleGeneralView.setName("labelTitleGeneralView"); // NOI18N

        buttonNewIncome.setBackground(new java.awt.Color(34, 206, 26));
        buttonNewIncome.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        buttonNewIncome.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/images/plusIcon.png"))); // NOI18N
        buttonNewIncome.setText("הכנסה חדשה ");
        buttonNewIncome.setName("buttonNewIncome"); // NOI18N
        buttonNewIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewIncomeActionPerformed(evt);
            }
        });

        generalViewPanel.setBackground(new java.awt.Color(242, 242, 242));
        generalViewPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));
        generalViewPanel.setForeground(new java.awt.Color(85, 96, 128));
        generalViewPanel.setToolTipText("");
        generalViewPanel.setName(""); // NOI18N

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "תקציב חודשי", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("השתמשת ב:");

        labelUsedBudget.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelUsedBudget.setForeground(new java.awt.Color(153, 153, 153));
        labelUsedBudget.setText("0.0");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("₪");
        jLabel22.setName("incomesLabel"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("מתוך:");

        labelOfBudget.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelOfBudget.setForeground(new java.awt.Color(153, 153, 153));
        labelOfBudget.setText("0.0");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("₪");
        jLabel25.setName("incomesLabel"); // NOI18N

        progressBarBudget.setToolTipText("");
        progressBarBudget.setValue(1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("0%");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("100%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelOfBudget)
                            .addComponent(labelUsedBudget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(progressBarBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel20)
                    .addComponent(labelUsedBudget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(labelOfBudget))
                    .addComponent(jLabel23))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(progressBarBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel19)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(242, 242, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "סיכום", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 206, 26));
        jLabel4.setText("הכנסות:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 206, 26));
        jLabel8.setText("₪");
        jLabel8.setName("incomesLabel"); // NOI18N

        labelIncomeAmount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelIncomeAmount.setForeground(new java.awt.Color(34, 206, 26));
        labelIncomeAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelIncomeAmount.setText("0.0");
        labelIncomeAmount.setName("incomesLabel"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 65, 21));
        jLabel5.setText("הוצאות:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 65, 21));
        jLabel9.setText("₪");
        jLabel9.setName("incomesLabel"); // NOI18N

        labelExpenseAmount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelExpenseAmount.setForeground(new java.awt.Color(242, 65, 21));
        labelExpenseAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelExpenseAmount.setText("0.0");
        labelExpenseAmount.setName("incomesLabel"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 96, 128));
        jLabel10.setText("סה\"כ:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 34)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 96, 128));
        jLabel11.setText("₪");
        jLabel11.setName("incomesLabel"); // NOI18N

        labelTransactionSum.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTransactionSum.setForeground(new java.awt.Color(85, 96, 128));
        labelTransactionSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTransactionSum.setText("0.0");
        labelTransactionSum.setName("incomesLabel"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("מציג מידע עבור");

        comboBoxDatesRange.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        comboBoxDatesRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "היום", "החודש", "השנה" }));
        comboBoxDatesRange.setSelectedIndex(1);
        comboBoxDatesRange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxDatesRangeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelTransactionSum, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelExpenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIncomeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxDatesRange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(labelIncomeAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(labelExpenseAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(labelTransactionSum))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxDatesRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout generalViewPanelLayout = new javax.swing.GroupLayout(generalViewPanel);
        generalViewPanel.setLayout(generalViewPanelLayout);
        generalViewPanelLayout.setHorizontalGroup(
            generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalViewPanelLayout.createSequentialGroup()
                .addGroup(generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalViewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(generalViewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        generalViewPanelLayout.setVerticalGroup(
            generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalViewPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        buttonNewExpense.setBackground(new java.awt.Color(242, 65, 21));
        buttonNewExpense.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        buttonNewExpense.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/images/minusIcon.png"))); // NOI18N
        buttonNewExpense.setText("הוצאה חדשה ");
        buttonNewExpense.setName("buttonNewExpense"); // NOI18N
        buttonNewExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(generalViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(buttonNewExpense)
                        .addGap(17, 17, 17)
                        .addComponent(buttonNewIncome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTitleGeneralView)
                        .addGap(450, 450, 450)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleGeneralView)
                .addGap(29, 29, 29)
                .addComponent(generalViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewIncome)
                    .addComponent(buttonNewExpense))
                .addContainerGap())
        );

        jPanel7.add(jPanel3);

        jPanel1.add(jPanel7);

        jTabbedPaneMenu.addTab("מבט על", null, jPanel1, "");
        jPanel1.getAccessibleContext().setAccessibleName("tab1");

        labelTitleTransactions.setBackground(new java.awt.Color(242, 241, 255));
        labelTitleTransactions.setForeground(new java.awt.Color(0, 102, 255));
        labelTitleTransactions.setName(""); // NOI18N
        labelTitleTransactions.setLayout(new javax.swing.BoxLayout(labelTitleTransactions, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBackground(new java.awt.Color(242, 241, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(1200, 575));

        jPanel8.setBackground(new java.awt.Color(242, 241, 255));
        jPanel8.setOpaque(false);

        labelTransactions.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelTransactions.setForeground(new java.awt.Color(85, 96, 128));
        labelTransactions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransactions.setText("תנועות");
        labelTransactions.setName("labelTitleGeneralView"); // NOI18N

        jPanel10.setBackground(new java.awt.Color(242, 241, 255));

        buttonNewExpense1.setBackground(new java.awt.Color(242, 65, 21));
        buttonNewExpense1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonNewExpense1.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewExpense1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/images/minusIcon.png"))); // NOI18N
        buttonNewExpense1.setText("הוצאה ");
        buttonNewExpense1.setName("buttonNewExpense"); // NOI18N
        buttonNewExpense1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewExpense1ActionPerformed(evt);
            }
        });

        datePickerToDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        datePickerToDate.setFormats(TransactionParser.TransactionDate.SIMPLE_DATE_FORMAT.toPattern());
        datePickerToDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerToDatePropertyChange(evt);
            }
        });

        comboBoxTransactionsData.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        comboBoxTransactionsData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "כל התנועות", "הכנסות", "הוצאות" }));
        comboBoxTransactionsData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTransactionsDataItemStateChanged(evt);
            }
        });

        buttonNewIncome1.setBackground(new java.awt.Color(34, 206, 26));
        buttonNewIncome1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonNewIncome1.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewIncome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/images/plusIcon.png"))); // NOI18N
        buttonNewIncome1.setText("הכנסה ");
        buttonNewIncome1.setName("buttonNewIncome"); // NOI18N
        buttonNewIncome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewIncome1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setText("מציג");

        datePickerFromDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        datePickerFromDate.setFormats(TransactionParser.TransactionDate.SIMPLE_DATE_FORMAT.toPattern());
        datePickerFromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerFromDatePropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("מתאריך");

        scrollbarTransactions.setBackground(new java.awt.Color(242, 242, 242));
        scrollbarTransactions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));

        panelTransactions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelScrollInnerContainer.add(panelTransactions);

        scrollbarTransactions.setViewportView(panelScrollInnerContainer);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("עד תאריך");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("תיאור");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("קטגוריה");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("תאריך");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setText("סכום");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setText("אמצעי תשלום");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel24.setText("מחיקה");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel24)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel21)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel6)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel12)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollbarTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonNewExpense1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonNewIncome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxTransactionsData, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePickerFromDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(datePickerToDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTransactionsData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickerFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickerToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNewIncome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNewExpense1))
                    .addComponent(scrollbarTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(labelTransactions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransactions)
                .addGap(43, 43, 43)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel8);

        labelTitleTransactions.add(jPanel9);

        jTabbedPaneMenu.addTab("תנועות", labelTitleTransactions);
        labelTitleTransactions.getAccessibleContext().setAccessibleName("tabIncomes");

        labelTitleBudget.setBackground(new java.awt.Color(242, 241, 255));
        labelTitleBudget.setForeground(new java.awt.Color(0, 102, 255));
        labelTitleBudget.setName(""); // NOI18N

        jPanel11.setBackground(new java.awt.Color(242, 241, 255));

        labelBudgetTitle.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelBudgetTitle.setForeground(new java.awt.Color(85, 96, 128));
        labelBudgetTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBudgetTitle.setText("תקציב");
        labelBudgetTitle.setName("labelTitleGeneralView"); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));
        jPanel2.setForeground(new java.awt.Color(85, 96, 128));

        checkBoxAlertBeforeException.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        checkBoxAlertBeforeException.setSelected(true);
        checkBoxAlertBeforeException.setText("התראה בעת חריגה");
        checkBoxAlertBeforeException.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        checkBoxEnableEdit.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        checkBoxEnableEdit.setSelected(true);
        checkBoxEnableEdit.setText("תקציב ניתן לעריכה");
        checkBoxEnableEdit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        spinnerAlertBefore.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spinnerAlertBefore.setValue(1000);

        spinnerBudgetAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jLabel17.setText("₪");
        jLabel17.setName("incomesLabel"); // NOI18N

        labelSetBudgetSum.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        labelSetBudgetSum.setText("סכום");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel16.setText("הגדר תקציב חדש ");

        buttonDefineBudget.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonDefineBudget.setText("הגדר");
        buttonDefineBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDefineBudgetActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jLabel26.setText("₪");
        jLabel26.setName("incomesLabel"); // NOI18N

        checkBoxAlertBeforeX.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        checkBoxAlertBeforeX.setSelected(true);
        checkBoxAlertBeforeX.setText("אזהרה כאשר נותרו");
        checkBoxAlertBeforeX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerBudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSetBudgetSum)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(156, 156, 156))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBoxEnableEdit)
                            .addComponent(checkBoxAlertBeforeException)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAlertBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxAlertBeforeX))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonDefineBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSetBudgetSum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerBudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(checkBoxEnableEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAlertBeforeException)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerAlertBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxAlertBeforeX))
                .addGap(12, 12, 12)
                .addComponent(buttonDefineBudget)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(labelBudgetTitle))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBudgetTitle)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        labelTitleBudget.add(jPanel11);

        jTabbedPaneMenu.addTab("תקציב", null, labelTitleBudget, "");
        labelTitleBudget.getAccessibleContext().setAccessibleName("tabExpenses");

        jScrollPane2.setViewportView(jTabbedPaneMenu);
        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewExpenseActionPerformed

        NewExpense expenseModal = new NewExpense();
        expenseModal.setLocationRelativeTo(this);
        buttonNewExpense.setEnabled(false);
        buttonNewIncome.setEnabled(false);
    }//GEN-LAST:event_buttonNewExpenseActionPerformed

    private void buttonNewIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewIncomeActionPerformed

        NewIncome incomeModal = new NewIncome();
        incomeModal.setLocationRelativeTo(this);
        buttonNewIncome.setEnabled(false);
        buttonNewExpense.setEnabled(false);
    }//GEN-LAST:event_buttonNewIncomeActionPerformed

    private void buttonNewIncome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewIncome1ActionPerformed

        NewIncome incomeModal = new NewIncome();
        incomeModal.setLocationRelativeTo(this);
        buttonNewIncome1.setEnabled(false);
        buttonNewExpense1.setEnabled(false);
    }//GEN-LAST:event_buttonNewIncome1ActionPerformed

    private void buttonNewExpense1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewExpense1ActionPerformed

        NewExpense expenseModal = new NewExpense();
        expenseModal.setLocationRelativeTo(this);
        buttonNewExpense1.setEnabled(false);
        buttonNewIncome1.setEnabled(false);
    }//GEN-LAST:event_buttonNewExpense1ActionPerformed

    private void comboBoxTransactionsDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTransactionsDataItemStateChanged
        // TODO add your handling code here:
        TransactionParser.sensitiveFillTransactionsPanel();
    }//GEN-LAST:event_comboBoxTransactionsDataItemStateChanged

    private void datePickerFromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerFromDatePropertyChange
        // TODO add your handling code here:
        if (MainWindow.program == null) {
            return;
        }
        if (getDatePickerFromDate().getDate().compareTo(getDatePickerToDate().getDate()) > 0) {
            getDatePickerFromDate().setDate(getDatePickerToDate().getDate());
        }
        TransactionParser.sensitiveFillTransactionsPanel();
    }//GEN-LAST:event_datePickerFromDatePropertyChange

    private void datePickerToDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerToDatePropertyChange
        // TODO add your handling code here:
        if (MainWindow.program == null) {
            return;
        }
        if (getDatePickerToDate().getDate().compareTo(getDatePickerFromDate().getDate()) < 0) {
            getDatePickerToDate().setDate(getDatePickerFromDate().getDate());
        }
        TransactionParser.sensitiveFillTransactionsPanel();
    }//GEN-LAST:event_datePickerToDatePropertyChange

    private void comboBoxDatesRangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxDatesRangeItemStateChanged
        // TODO add your handling code here:
        TransactionParser.sesitiveFillTransactionsAmount();
    }//GEN-LAST:event_comboBoxDatesRangeItemStateChanged

    private void buttonDefineBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDefineBudgetActionPerformed

        if (checkBudgetValues()) {
            setLabelOfBudget(Double.parseDouble(getSpinnerBudgetAmount().getValue().toString()));
            getLabelSetBudgetSum().setForeground(Color.BLACK);

            if (!getCheckBoxEnableEdit().isSelected()) {
                Budget.setAllBudgetComponentsDisabled();
            }
            JOptionPane.showMessageDialog(null, "התקציב הוגדר בהצלחה");

            try {
                Budget.SerializationHandler.writeBudgetToDisk(new Budget(Double.parseDouble(getSpinnerBudgetAmount().getValue().toString()),
                        getCheckBoxEnableEdit().isSelected(), getCheckBoxAlertBeforeException().isSelected(), getCheckBoxAlertBeforeX().isSelected(),
                        Double.parseDouble(getSpinnerAlertBefore().getValue().toString())));
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonDefineBudgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                program = new MainWindow();
                program.setVisible(true);
                TransactionParser.transactionChangesRoutine();
                TransactionParser.updateProgressBar();
                Budget.budgetChangesRutine();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDefineBudget;
    private javax.swing.JButton buttonNewExpense;
    private javax.swing.JButton buttonNewExpense1;
    private javax.swing.JButton buttonNewIncome;
    private javax.swing.JButton buttonNewIncome1;
    private javax.swing.JCheckBox checkBoxAlertBeforeException;
    private javax.swing.JCheckBox checkBoxAlertBeforeX;
    private javax.swing.JCheckBox checkBoxEnableEdit;
    private javax.swing.JComboBox<String> comboBoxDatesRange;
    private javax.swing.JComboBox<String> comboBoxTransactionsData;
    private org.jdesktop.swingx.JXDatePicker datePickerFromDate;
    private org.jdesktop.swingx.JXDatePicker datePickerToDate;
    private javax.swing.JPanel generalViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    private javax.swing.JLabel labelBudgetTitle;
    private javax.swing.JLabel labelExpenseAmount;
    private javax.swing.JLabel labelIncomeAmount;
    private javax.swing.JLabel labelOfBudget;
    private javax.swing.JLabel labelSetBudgetSum;
    private javax.swing.JPanel labelTitleBudget;
    private javax.swing.JLabel labelTitleGeneralView;
    private javax.swing.JPanel labelTitleTransactions;
    private javax.swing.JLabel labelTransactionSum;
    private javax.swing.JLabel labelTransactions;
    private javax.swing.JLabel labelUsedBudget;
    private javax.swing.JPanel panelScrollInnerContainer;
    private javax.swing.JPanel panelTransactions;
    private javax.swing.JProgressBar progressBarBudget;
    private javax.swing.JScrollPane scrollbarTransactions;
    private javax.swing.JSpinner spinnerAlertBefore;
    private javax.swing.JSpinner spinnerBudgetAmount;
    // End of variables declaration//GEN-END:variables

    public static MainWindow program;
    private static double ballance = 0;

    public static MainWindow getProgram() {
        return program;
    }

    private static void setProgram(MainWindow program) {
        MainWindow.program = program;
    }

    public static double getBallance() {
        return ballance;
    }

    public static void setBallance(double ballance) {
        MainWindow.ballance = ballance;
    }

    public JButton getButtonNewExpense() {
        return buttonNewExpense;
    }

    public void setButtonNewExpense(JButton buttonNewExpense) {
        this.buttonNewExpense = buttonNewExpense;
    }

    public JButton getButtonNewExpense1() {
        return buttonNewExpense1;
    }

    public void setButtonNewExpense1(JButton buttonNewExpense1) {
        this.buttonNewExpense1 = buttonNewExpense1;
    }

    public JButton getButtonNewIncome() {
        return buttonNewIncome;
    }

    public void setButtonNewIncome(JButton buttonNewIncome) {
        this.buttonNewIncome = buttonNewIncome;
    }

    public JButton getButtonNewIncome1() {
        return buttonNewIncome1;
    }

    public void setButtonNewIncome1(JButton buttonNewIncome1) {
        this.buttonNewIncome1 = buttonNewIncome1;
    }

    public JComboBox<String> getComboBoxTransactionsData() {
        return comboBoxTransactionsData;
    }

    public void setComboBoxTransactionsData(JComboBox<String> comboBoxTransactionsData) {
        this.comboBoxTransactionsData = comboBoxTransactionsData;
    }

    public JComboBox<String> getComboBoxDatesRange() {
        return comboBoxDatesRange;
    }

    public void setComboBoxDatesRange(JComboBox<String> comboBoxDatesRange) {
        this.comboBoxDatesRange = comboBoxDatesRange;
    }

    public JPanel getPanelScrollInnerContainer() {
        return panelScrollInnerContainer;
    }

    public void setPanelScrollInnerContainer(JPanel panelScrollInnerContainer) {
        this.panelScrollInnerContainer = panelScrollInnerContainer;
    }

    public JScrollPane getScrollbarTransactions() {
        return scrollbarTransactions;
    }

    public void setScrollbarTransactions(JScrollPane scrollbarTransactions) {
        this.scrollbarTransactions = scrollbarTransactions;
    }

    public JPanel getPanelTransactions() {
        return panelTransactions;
    }

    public void setPanelTransactions(JPanel panelTransactions) {
        this.panelTransactions = panelTransactions;
    }

    public JLabel getLabelExpenseAmount() {
        return labelExpenseAmount;
    }

    public void setLabelExpenseAmount(JLabel labelExpenseAmount) {
        this.labelExpenseAmount = labelExpenseAmount;
    }

    public void setLabelExpenseAmount(String expenseAmount) {
        this.getLabelExpenseAmount().setText(expenseAmount);
    }

    public void setLabelExpenseAmount(double expenseAmount) {
        this.getLabelExpenseAmount().setText(String.format("%.2f", expenseAmount));
    }

    public JLabel getLabelIncomeAmount() {
        return labelIncomeAmount;
    }

    public void setLabelIncomeAmount(JLabel labelIncomeAmount) {
        this.labelIncomeAmount = labelIncomeAmount;
    }

    public void setLabelIncomeAmount(String incomeAmount) {
        this.getLabelIncomeAmount().setText(incomeAmount);
    }

    public void setLabelIncomeAmount(double incomeAmount) {
        this.getLabelIncomeAmount().setText(String.format("%.2f", incomeAmount));
    }

    public JLabel getLabelTransactionSum() {
        return labelTransactionSum;
    }

    public void setLabelTransactionSum(JLabel labelTransactionSum) {
        this.labelTransactionSum = labelTransactionSum;
    }

    public void setLabelTransactionSum(String transactionSum) {
        this.getLabelTransactionSum().setText(transactionSum);
    }

    public void setLabelTransactionSum(double transactionSum) {
        this.getLabelTransactionSum().setText(String.format("%.2f", transactionSum));
    }

    public JPanel getGeneralViewPanel() {
        return generalViewPanel;
    }

    public void setGeneralViewPanel(JPanel generalViewPanel) {
        this.generalViewPanel = generalViewPanel;
    }

    public void updateGeneralViewPanel() {
        getGeneralViewPanel().revalidate();
        getGeneralViewPanel().repaint();
    }

    public JXDatePicker getDatePickerFromDate() {
        return datePickerFromDate;
    }

    public void setDatePickerFromDate(JXDatePicker datePickerFromDate) {
        this.datePickerFromDate = datePickerFromDate;
    }

    public JXDatePicker getDatePickerToDate() {
        return datePickerToDate;
    }

    public void setDatePickerToDate(JXDatePicker datePickerToDate) {
        this.datePickerToDate = datePickerToDate;
    }

    public JLabel getLabelOfBudget() {
        return labelOfBudget;
    }

    public void setLabelOfBudget(JLabel labelOfBudget) {
        this.labelOfBudget = labelOfBudget;
    }

    public void setLabelOfBudget(double budgetSum) {
        this.getLabelOfBudget().setText(String.format("%.2f", budgetSum));
    }

    public JSpinner getSpinnerBudgetAmount() {
        return spinnerBudgetAmount;
    }

    public void setSpinnerBudgetAmount(JSpinner spinnerBudgetAmount) {
        this.spinnerBudgetAmount = spinnerBudgetAmount;
    }

    public JSpinner getSpinnerAlertBefore() {
        return spinnerAlertBefore;
    }

    public void setSpinnerAlertBefore(JSpinner spinnerAlertBefore) {
        this.spinnerAlertBefore = spinnerAlertBefore;
    }

    public JLabel getLabelSetBudgetSum() {
        return labelSetBudgetSum;
    }

    public void setLabelSetBudgetSum(JLabel labelSetBudgetSum) {
        this.labelSetBudgetSum = labelSetBudgetSum;
    }

    public JCheckBox getCheckBoxAlertBeforeX() {
        return checkBoxAlertBeforeX;
    }

    public void setCheckBoxAlertBeforeX(JCheckBox checkBoxAlertBeforeX) {
        this.checkBoxAlertBeforeX = checkBoxAlertBeforeX;
    }

    public JCheckBox getCheckBoxAlertBeforeException() {
        return checkBoxAlertBeforeException;
    }

    public void setCheckBoxAlertBeforeException(JCheckBox checkBoxAlertBeforeException) {
        this.checkBoxAlertBeforeException = checkBoxAlertBeforeException;
    }

    public JCheckBox getCheckBoxEnableEdit() {
        return checkBoxEnableEdit;
    }

    public void setCheckBoxEnableEdit(JCheckBox checkBoxEnableEdit) {
        this.checkBoxEnableEdit = checkBoxEnableEdit;
    }

    public JLabel getLabelUsedBudget() {
        return labelUsedBudget;
    }

    public void setLabelUsedBudget(JLabel labelUsedBudget) {
        this.labelUsedBudget = labelUsedBudget;
    }

    public void setLabelUsedBudget(double usedBudget) {
        this.getLabelUsedBudget().setText(String.format("%.2f", usedBudget));
    }

    public JProgressBar getProgressBarBudget() {
        return progressBarBudget;
    }

    public void setProgressBarBudget(JProgressBar progressBarBudget) {
        this.progressBarBudget = progressBarBudget;
    }

    public JButton getButtonDefineBudget() {
        return buttonDefineBudget;
    }

    public void setButtonDefineBudget(JButton buttonDefineBudget) {
        this.buttonDefineBudget = buttonDefineBudget;
    }

    public boolean checkBudgetValues() {

        if (Double.parseDouble(getSpinnerBudgetAmount().getValue().toString()) == 0) {

            getLabelSetBudgetSum().setForeground(Color.RED);
            return false;
        }
        return true;
    }

    public class CheckBoxHandler implements ItemListener {

        public void itemStateChanged(ItemEvent e) {

            if (checkBoxAlertBeforeX.isSelected()) {
                spinnerAlertBefore.setEnabled(true);
            } else {
                spinnerAlertBefore.setEnabled(false);
            }
        }
    }
}
