/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

import java.awt.ComponentOrientation;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Yair Ariel
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("logoIcon.png")).getImage());
        setLocationRelativeTo(null);
        Locale hebrew = new Locale("iw", "IL");
        ComponentOrientation hebrewOri1entation = ComponentOrientation.getOrientation(hebrew);
        jTabbedPaneMenu.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        // General view components
        ((JLabel) comboBoxDatesRange.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);

        // Transactions components
        datePickerFromDate.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        datePickerToDate.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        comboBoxTransactionsData.applyComponentOrientation(hebrewOri1entation);
        ((JLabel) comboBoxTransactionsData.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);

        // Budget components
        spinnerBudgetAmount.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        spinnerAlertBefore.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        // Calculator components
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelTitleGeneralView = new javax.swing.JLabel();
        generalViewPanel = new javax.swing.JPanel();
        comboBoxDatesRange = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelIncomeAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelExpenseAmount = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTransactionSum = new javax.swing.JLabel();
        buttonNewIncome = new javax.swing.JButton();
        buttonNewExpense = new javax.swing.JButton();
        labelTitleTransactions = new javax.swing.JPanel();
        labelTransactions = new javax.swing.JLabel();
        scrollbarTransactions = new javax.swing.JScrollPane();
        panelScrollInnerContainer = new javax.swing.JPanel();
        panelTransactions = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datePickerFromDate = new org.jdesktop.swingx.JXDatePicker(new Date(110,0,1));
        datePickerToDate = new org.jdesktop.swingx.JXDatePicker(new Date(130,11,30));
        jLabel15 = new javax.swing.JLabel();
        comboBoxTransactionsData = new javax.swing.JComboBox<>();
        buttonNewIncome1 = new javax.swing.JButton();
        buttonNewExpense1 = new javax.swing.JButton();
        labelTitleBudget = new javax.swing.JPanel();
        labelBudget = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkBoxAlertBeforeException = new javax.swing.JCheckBox();
        checkBoxAlertBeforeX = new javax.swing.JCheckBox();
        spinnerAlertBefore = new javax.swing.JSpinner();
        spinnerBudgetAmount = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        buttonDefineBudjet = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelCalculator = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashew - Main Menu");
        setBackground(new java.awt.Color(242, 239, 239));
        setResizable(false);

        jTabbedPaneMenu.setBackground(new java.awt.Color(251, 248, 255));
        jTabbedPaneMenu.setForeground(new java.awt.Color(85, 96, 128));
        jTabbedPaneMenu.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jTabbedPaneMenu.setName(""); // NOI18N
        jTabbedPaneMenu.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(242, 241, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        labelTitleGeneralView.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelTitleGeneralView.setForeground(new java.awt.Color(85, 96, 128));
        labelTitleGeneralView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleGeneralView.setText("מבט על");
        labelTitleGeneralView.setName("labelTitleGeneralView"); // NOI18N

        generalViewPanel.setBackground(new java.awt.Color(242, 242, 242));
        generalViewPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));
        generalViewPanel.setForeground(new java.awt.Color(85, 96, 128));
        generalViewPanel.setToolTipText("");
        generalViewPanel.setName(""); // NOI18N

        comboBoxDatesRange.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        comboBoxDatesRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "היום", "החודש", "השנה" }));
        comboBoxDatesRange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxDatesRangeItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("מציג מידע עבור");

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "תקציב", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("השתמשת ב");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("0.0");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("₪");
        jLabel22.setName("incomesLabel"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("מתוך");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("0.0");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("₪");
        jLabel25.setName("incomesLabel"); // NOI18N

        jProgressBar1.setToolTipText("");
        jProgressBar1.setValue(32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("0%");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("100%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 192, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel24))
                    .addComponent(jLabel23))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel19)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(242, 242, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "סיכום", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 206, 26));
        jLabel4.setText("הכנסות:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 206, 26));
        jLabel8.setText("₪");
        jLabel8.setName("incomesLabel"); // NOI18N

        labelIncomeAmount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelIncomeAmount.setForeground(new java.awt.Color(34, 206, 26));
        labelIncomeAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelIncomeAmount.setText("0.0");
        labelIncomeAmount.setName("incomesLabel"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 65, 21));
        jLabel5.setText("הוצאות:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 65, 21));
        jLabel9.setText("₪");
        jLabel9.setName("incomesLabel"); // NOI18N

        labelExpenseAmount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelExpenseAmount.setForeground(new java.awt.Color(242, 65, 21));
        labelExpenseAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelExpenseAmount.setText("0.0");
        labelExpenseAmount.setName("incomesLabel"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 96, 128));
        jLabel10.setText("סה\"כ:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 34)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 96, 128));
        jLabel11.setText("₪");
        jLabel11.setName("incomesLabel"); // NOI18N

        labelTransactionSum.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTransactionSum.setForeground(new java.awt.Color(85, 96, 128));
        labelTransactionSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTransactionSum.setText("0.0");
        labelTransactionSum.setName("incomesLabel"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelIncomeAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelExpenseAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelTransactionSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(labelIncomeAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(labelExpenseAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(labelTransactionSum))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout generalViewPanelLayout = new javax.swing.GroupLayout(generalViewPanel);
        generalViewPanel.setLayout(generalViewPanelLayout);
        generalViewPanelLayout.setHorizontalGroup(
            generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalViewPanelLayout.createSequentialGroup()
                .addGroup(generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalViewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(generalViewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxDatesRange, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        generalViewPanelLayout.setVerticalGroup(
            generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalViewPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalViewPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxDatesRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(generalViewPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        buttonNewIncome.setBackground(new java.awt.Color(34, 206, 26));
        buttonNewIncome.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        buttonNewIncome.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/plusIcon.png"))); // NOI18N
        buttonNewIncome.setText("הכנסה חדשה ");
        buttonNewIncome.setName("buttonNewIncome"); // NOI18N
        buttonNewIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewIncomeActionPerformed(evt);
            }
        });

        buttonNewExpense.setBackground(new java.awt.Color(242, 65, 21));
        buttonNewExpense.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        buttonNewExpense.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/minusIcon.png"))); // NOI18N
        buttonNewExpense.setText("הוצאה חדשה ");
        buttonNewExpense.setName("buttonNewExpense"); // NOI18N
        buttonNewExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(labelTitleGeneralView))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(buttonNewExpense)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNewIncome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleGeneralView)
                .addGap(29, 29, 29)
                .addComponent(generalViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewIncome)
                    .addComponent(buttonNewExpense))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("מבט על", null, jPanel1, "");
        jPanel1.getAccessibleContext().setAccessibleName("tab1");

        labelTitleTransactions.setBackground(new java.awt.Color(242, 241, 255));
        labelTitleTransactions.setForeground(new java.awt.Color(0, 102, 255));
        labelTitleTransactions.setName(""); // NOI18N

        labelTransactions.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelTransactions.setForeground(new java.awt.Color(85, 96, 128));
        labelTransactions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransactions.setText("תנועות");
        labelTransactions.setName("labelTitleGeneralView"); // NOI18N

        scrollbarTransactions.setBackground(new java.awt.Color(242, 242, 242));
        scrollbarTransactions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));

        panelTransactions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelScrollInnerContainer.add(panelTransactions);

        scrollbarTransactions.setViewportView(panelScrollInnerContainer);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("מתאריך");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("עד תאריך");

        datePickerFromDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        datePickerFromDate.setFormats(TransactionParser.TransactionDate.SIMPLE_DATE_FORMAT.toPattern());
        datePickerFromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerFromDatePropertyChange(evt);
            }
        });

        datePickerToDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        datePickerToDate.setFormats(TransactionParser.TransactionDate.SIMPLE_DATE_FORMAT.toPattern());
        datePickerToDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerToDatePropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setText("מציג");

        comboBoxTransactionsData.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        comboBoxTransactionsData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "כל התנועות", "הכנסות", "הוצאות" }));
        comboBoxTransactionsData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTransactionsDataItemStateChanged(evt);
            }
        });

        buttonNewIncome1.setBackground(new java.awt.Color(34, 206, 26));
        buttonNewIncome1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonNewIncome1.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewIncome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/plusIcon.png"))); // NOI18N
        buttonNewIncome1.setText("הכנסה ");
        buttonNewIncome1.setName("buttonNewIncome"); // NOI18N
        buttonNewIncome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewIncome1ActionPerformed(evt);
            }
        });

        buttonNewExpense1.setBackground(new java.awt.Color(242, 65, 21));
        buttonNewExpense1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonNewExpense1.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewExpense1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebudgetmanager/minusIcon.png"))); // NOI18N
        buttonNewExpense1.setText("הוצאה ");
        buttonNewExpense1.setName("buttonNewExpense"); // NOI18N
        buttonNewExpense1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewExpense1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labelTitleTransactionsLayout = new javax.swing.GroupLayout(labelTitleTransactions);
        labelTitleTransactions.setLayout(labelTitleTransactionsLayout);
        labelTitleTransactionsLayout.setHorizontalGroup(
            labelTitleTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelTitleTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollbarTransactions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(labelTitleTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datePickerFromDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxTransactionsData, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datePickerToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewIncome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewExpense1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(labelTitleTransactionsLayout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(labelTransactions)
                .addContainerGap(523, Short.MAX_VALUE))
        );
        labelTitleTransactionsLayout.setVerticalGroup(
            labelTitleTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelTitleTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransactions)
                .addGap(116, 116, 116)
                .addGroup(labelTitleTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelTitleTransactionsLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTransactionsData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickerFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickerToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(buttonNewIncome1)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNewExpense1))
                    .addComponent(scrollbarTransactions))
                .addContainerGap())
        );

        jTabbedPaneMenu.addTab("תנועות", labelTitleTransactions);
        labelTitleTransactions.getAccessibleContext().setAccessibleName("tabIncomes");

        labelTitleBudget.setBackground(new java.awt.Color(242, 241, 255));
        labelTitleBudget.setForeground(new java.awt.Color(0, 102, 255));
        labelTitleBudget.setName(""); // NOI18N

        labelBudget.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelBudget.setForeground(new java.awt.Color(85, 96, 128));
        labelBudget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBudget.setText("תקציב");
        labelBudget.setName("labelTitleGeneralView"); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));
        jPanel2.setForeground(new java.awt.Color(85, 96, 128));

        checkBoxAlertBeforeException.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        checkBoxAlertBeforeException.setSelected(true);
        checkBoxAlertBeforeException.setText("התראה בעת חריגה");
        checkBoxAlertBeforeException.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        checkBoxAlertBeforeX.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        checkBoxAlertBeforeX.setSelected(true);
        checkBoxAlertBeforeX.setText("אזהרה כאשר נותרו");
        checkBoxAlertBeforeX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        spinnerAlertBefore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        spinnerBudgetAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel17.setText("₪");
        jLabel17.setName("incomesLabel"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setText("סכום");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("הגדר תקציב חדש ");

        buttonDefineBudjet.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonDefineBudjet.setText("הגדר");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel26.setText("₪");
        jLabel26.setName("incomesLabel"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBoxAlertBeforeException)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerBudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerAlertBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxAlertBeforeX)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(165, 165, 165))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDefineBudjet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerBudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkBoxAlertBeforeException)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxAlertBeforeX)
                    .addComponent(spinnerAlertBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(buttonDefineBudjet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 96, 128), 2, true));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout labelTitleBudgetLayout = new javax.swing.GroupLayout(labelTitleBudget);
        labelTitleBudget.setLayout(labelTitleBudgetLayout);
        labelTitleBudgetLayout.setHorizontalGroup(
            labelTitleBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelTitleBudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelTitleBudgetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBudget)
                .addGap(446, 446, 446))
        );
        labelTitleBudgetLayout.setVerticalGroup(
            labelTitleBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelTitleBudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBudget)
                .addGap(18, 118, Short.MAX_VALUE)
                .addGroup(labelTitleBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPaneMenu.addTab("תקציב", null, labelTitleBudget, "");
        labelTitleBudget.getAccessibleContext().setAccessibleName("tabExpenses");

        jPanel3.setBackground(new java.awt.Color(242, 241, 255));

        labelCalculator.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        labelCalculator.setForeground(new java.awt.Color(85, 96, 128));
        labelCalculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCalculator.setText("מחשבון");
        labelCalculator.setName("labelTitleGeneralView"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(521, Short.MAX_VALUE)
                .addComponent(labelCalculator)
                .addGap(442, 442, 442))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCalculator)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("מחשבון", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewExpenseActionPerformed

        NewExpense expenseModal = new NewExpense();
        expenseModal.setLocationRelativeTo(this);
        buttonNewExpense.setEnabled(false);
        buttonNewIncome.setEnabled(false);
    }//GEN-LAST:event_buttonNewExpenseActionPerformed

    private void buttonNewIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewIncomeActionPerformed

        NewIncome incomeModal = new NewIncome();
        incomeModal.setLocationRelativeTo(this);
        buttonNewIncome.setEnabled(false);
        buttonNewExpense.setEnabled(false);
    }//GEN-LAST:event_buttonNewIncomeActionPerformed

    private void buttonNewIncome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewIncome1ActionPerformed

        NewIncome incomeModal = new NewIncome();
        incomeModal.setLocationRelativeTo(this);
        buttonNewIncome1.setEnabled(false);
        buttonNewExpense1.setEnabled(false);
    }//GEN-LAST:event_buttonNewIncome1ActionPerformed

    private void buttonNewExpense1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewExpense1ActionPerformed

        NewExpense expenseModal = new NewExpense();
        expenseModal.setLocationRelativeTo(this);
        buttonNewExpense1.setEnabled(false);
        buttonNewIncome1.setEnabled(false);
    }//GEN-LAST:event_buttonNewExpense1ActionPerformed

    private void comboBoxTransactionsDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTransactionsDataItemStateChanged
        // TODO add your handling code here:
        TransactionParser.sensitiveFillTransactionsPanel();
    }//GEN-LAST:event_comboBoxTransactionsDataItemStateChanged

    private void datePickerFromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerFromDatePropertyChange
        // TODO add your handling code here:
        if (MainWindow.program == null) {
            return;
        }
        if (getDatePickerFromDate().getDate().compareTo(getDatePickerToDate().getDate()) > 0) {
            getDatePickerFromDate().setDate(getDatePickerToDate().getDate());
        }
        TransactionParser.sensitiveFillTransactionsPanel();
    }//GEN-LAST:event_datePickerFromDatePropertyChange

    private void datePickerToDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerToDatePropertyChange
        // TODO add your handling code here:
        if (MainWindow.program == null) {
            return;
        }
        if (getDatePickerToDate().getDate().compareTo(getDatePickerFromDate().getDate()) < 0) {
            getDatePickerToDate().setDate(getDatePickerFromDate().getDate());
        }
        TransactionParser.sensitiveFillTransactionsPanel();
    }//GEN-LAST:event_datePickerToDatePropertyChange

    private void comboBoxDatesRangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxDatesRangeItemStateChanged
        // TODO add your handling code here:
        TransactionParser.sesitiveFillTransactionsAmount();
    }//GEN-LAST:event_comboBoxDatesRangeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                program = new MainWindow();
                program.setVisible(true);
                TransactionParser.transactionChangesRoutine();
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDefineBudjet;
    private javax.swing.JButton buttonNewExpense;
    private javax.swing.JButton buttonNewExpense1;
    private javax.swing.JButton buttonNewIncome;
    private javax.swing.JButton buttonNewIncome1;
    private javax.swing.JCheckBox checkBoxAlertBeforeException;
    private javax.swing.JCheckBox checkBoxAlertBeforeX;
    private javax.swing.JComboBox<String> comboBoxDatesRange;
    private javax.swing.JComboBox<String> comboBoxTransactionsData;
    private org.jdesktop.swingx.JXDatePicker datePickerFromDate;
    private org.jdesktop.swingx.JXDatePicker datePickerToDate;
    private javax.swing.JPanel generalViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    private javax.swing.JLabel labelBudget;
    private javax.swing.JLabel labelCalculator;
    private javax.swing.JLabel labelExpenseAmount;
    private javax.swing.JLabel labelIncomeAmount;
    private javax.swing.JPanel labelTitleBudget;
    private javax.swing.JLabel labelTitleGeneralView;
    private javax.swing.JPanel labelTitleTransactions;
    private javax.swing.JLabel labelTransactionSum;
    private javax.swing.JLabel labelTransactions;
    private javax.swing.JPanel panelScrollInnerContainer;
    private javax.swing.JPanel panelTransactions;
    private javax.swing.JScrollPane scrollbarTransactions;
    private javax.swing.JSpinner spinnerAlertBefore;
    private javax.swing.JSpinner spinnerBudgetAmount;
    // End of variables declaration//GEN-END:variables

    static MainWindow program;

    private static double ballance = 0;
//    Calendar c = Calendar.getInstance();
//    c.(Calendar.DAY_OF_MONTH, 1);
//    System.out.println(c.getTime());

    public static MainWindow getProgram() {
        return program;
    }

    private static void setProgram(MainWindow program) {
        MainWindow.program = program;
    }

    public static double getBallance() {
        return ballance;
    }

    public static void setBallance(double ballance) {
        MainWindow.ballance = ballance;
    }

    public JButton getButtonNewExpense() {
        return buttonNewExpense;
    }

    public void setButtonNewExpense(JButton buttonNewExpense) {
        this.buttonNewExpense = buttonNewExpense;
    }

    public JButton getButtonNewExpense1() {
        return buttonNewExpense1;
    }

    public void setButtonNewExpense1(JButton buttonNewExpense1) {
        this.buttonNewExpense1 = buttonNewExpense1;
    }

    public JButton getButtonNewIncome() {
        return buttonNewIncome;
    }

    public void setButtonNewIncome(JButton buttonNewIncome) {
        this.buttonNewIncome = buttonNewIncome;
    }

    public JButton getButtonNewIncome1() {
        return buttonNewIncome1;
    }

    public void setButtonNewIncome1(JButton buttonNewIncome1) {
        this.buttonNewIncome1 = buttonNewIncome1;
    }

    public JComboBox<String> getComboBoxTransactionsData() {
        return comboBoxTransactionsData;
    }

    public void setComboBoxTransactionsData(JComboBox<String> comboBoxTransactionsData) {
        this.comboBoxTransactionsData = comboBoxTransactionsData;
    }

    public JComboBox<String> getComboBoxDatesRange() {
        return comboBoxDatesRange;
    }

    public void setComboBoxDatesRange(JComboBox<String> comboBoxDatesRange) {
        this.comboBoxDatesRange = comboBoxDatesRange;
    }

    public JPanel getPanelScrollInnerContainer() {
        return panelScrollInnerContainer;
    }

    public void setPanelScrollInnerContainer(JPanel panelScrollInnerContainer) {
        this.panelScrollInnerContainer = panelScrollInnerContainer;
    }

    public JScrollPane getScrollbarTransactions() {
        return scrollbarTransactions;
    }

    public void setScrollbarTransactions(JScrollPane scrollbarTransactions) {
        this.scrollbarTransactions = scrollbarTransactions;
    }

    public JPanel getPanelTransactions() {
        return panelTransactions;
    }

    public void setPanelTransactions(JPanel panelTransactions) {
        this.panelTransactions = panelTransactions;
    }

    public JLabel getLabelExpenseAmount() {
        return labelExpenseAmount;
    }

    public void setLabelExpenseAmount(JLabel labelExpenseAmount) {
        this.labelExpenseAmount = labelExpenseAmount;
    }

    public void setLabelExpenseAmount(String expenseAmount) {
        this.getLabelExpenseAmount().setText(expenseAmount);
    }

    public void setLabelExpenseAmount(double expenseAmount) {
        this.getLabelExpenseAmount().setText(String.format("%.2f", expenseAmount));
    }

    public JLabel getLabelIncomeAmount() {
        return labelIncomeAmount;
    }

    public void setLabelIncomeAmount(JLabel labelIncomeAmount) {
        this.labelIncomeAmount = labelIncomeAmount;
    }

    public void setLabelIncomeAmount(String incomeAmount) {
        this.getLabelIncomeAmount().setText(incomeAmount);
    }

    public void setLabelIncomeAmount(double incomeAmount) {
        this.getLabelIncomeAmount().setText(String.format("%.2f", incomeAmount));
    }

    public JLabel getLabelTransactionSum() {
        return labelTransactionSum;
    }

    public void setLabelTransactionSum(JLabel labelTransactionSum) {
        this.labelTransactionSum = labelTransactionSum;
    }

    public void setLabelTransactionSum(String transactionSum) {
        this.getLabelTransactionSum().setText(transactionSum);
    }

    public void setLabelTransactionSum(double transactionSum) {
        this.getLabelTransactionSum().setText(String.format("%.2f", transactionSum));
    }

    public JPanel getGeneralViewPanel() {
        return generalViewPanel;
    }

    public void setGeneralViewPanel(JPanel generalViewPanel) {
        this.generalViewPanel = generalViewPanel;
    }

    public void updateGeneralViewPanel() {
        getGeneralViewPanel().revalidate();
        getGeneralViewPanel().repaint();
    }

    public JXDatePicker getDatePickerFromDate() {
        return datePickerFromDate;
    }

    public void setDatePickerFromDate(JXDatePicker datePickerFromDate) {
        this.datePickerFromDate = datePickerFromDate;
    }

    public JXDatePicker getDatePickerToDate() {
        return datePickerToDate;
    }

    public void setDatePickerToDate(JXDatePicker datePickerToDate) {
        this.datePickerToDate = datePickerToDate;
    }

}
