/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudgetmanager;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Yair Ariel
 */
public class NewIncome extends JDialog {

    /**
     * Creates new form NewIncome
     */
    public NewIncome() {
        super(MainWindow.getProgram());
        setIconPath("");
        setAmount(0.0);
        setDate(new GregorianCalendar());
        setIncomeDescription("");
        setIncomeMethod("");
        setIncomeSource("");
        initComponents();
        setVisible(true);
        setIconImage(new ImageIcon(getClass().getResource("images/logoIcon.png")).getImage());
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Locale hebrew = new Locale("iw", "IL");
        ComponentOrientation hebrewOri1entation = ComponentOrientation.getOrientation(hebrew);
        comboBoxIncomeSource.applyComponentOrientation(hebrewOri1entation);
        ((JLabel) comboBoxIncomeSource.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);
        comboBoxIncomeMethod.applyComponentOrientation(hebrewOri1entation);
        ((JLabel) comboBoxIncomeMethod.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);
        datePickerIncome.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        textBoxIncomeComments.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        spinnerIncomeSum.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelIncomeSource = new javax.swing.JLabel();
        comboBoxIncomeSource = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        datePickerIncome = new org.jdesktop.swingx.JXDatePicker(new Date());
        labelIncomeMethod = new javax.swing.JLabel();
        comboBoxIncomeMethod = new javax.swing.JComboBox<>();
        labelIncomeAmount = new javax.swing.JLabel();
        spinnerIncomeSum = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textBoxIncomeComments = new javax.swing.JTextField();
        buttonIncomeCancel = new javax.swing.JButton();
        buttonAddIncome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cashew - New Income");
        setMinimumSize(null);

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 500));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorRemoved(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 96, 128));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("הכנסה חדשה");
        jLabel6.setName("jLabel6"); // NOI18N

        labelIncomeSource.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelIncomeSource.setText("מקור");

        comboBoxIncomeSource.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        comboBoxIncomeSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "בחר מקור", "ביטוח לאומי", "זכיות", "משכורת", "מתנה", "פנסיה", "קצבה", "שכר דירה", "אחר" }));
        comboBoxIncomeSource.setMaximumSize(new java.awt.Dimension(220, 36));
        comboBoxIncomeSource.setMinimumSize(new java.awt.Dimension(220, 36));
        comboBoxIncomeSource.setPreferredSize(new java.awt.Dimension(220, 36));
        comboBoxIncomeSource.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxIncomeSourceItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel4.setText("תאריך");

        datePickerIncome.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        datePickerIncome.setMaximumSize(new java.awt.Dimension(160, 38));
        datePickerIncome.setMinimumSize(new java.awt.Dimension(160, 38));
        datePickerIncome.setPreferredSize(new java.awt.Dimension(160, 38));
        datePickerIncome.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerIncomePropertyChange(evt);
            }
        });

        labelIncomeMethod.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelIncomeMethod.setText("אמצעי תשלום");

        comboBoxIncomeMethod.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        comboBoxIncomeMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "בחר אמצעי תשלום", "מזומן", "צ'ק", "העברה בנקאית", "אשראי" }));
        comboBoxIncomeMethod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxIncomeMethodItemStateChanged(evt);
            }
        });

        labelIncomeAmount.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelIncomeAmount.setText("סכום");

        spinnerIncomeSum.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        spinnerIncomeSum.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 5.0d));
        spinnerIncomeSum.setMaximumSize(new java.awt.Dimension(150, 36));
        spinnerIncomeSum.setMinimumSize(new java.awt.Dimension(150, 36));
        spinnerIncomeSum.setName(""); // NOI18N
        spinnerIncomeSum.setPreferredSize(new java.awt.Dimension(150, 36));
        spinnerIncomeSum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerIncomeSumStateChanged(evt);
            }
        });
        spinnerIncomeSum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinnerIncomeSumFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabel11.setText("₪");
        jLabel11.setName("incomesLabel"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setText("תיאור");

        textBoxIncomeComments.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        textBoxIncomeComments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBoxIncomeCommentsKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBoxIncomeCommentsKeyReleased(evt);
            }
        });

        buttonIncomeCancel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonIncomeCancel.setText("ביטול");
        buttonIncomeCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncomeCancelActionPerformed(evt);
            }
        });

        buttonAddIncome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonAddIncome.setText("הוסף");
        buttonAddIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddIncomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(textBoxIncomeComments, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(datePickerIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIncomeSource, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxIncomeSource, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerIncomeSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelIncomeAmount)))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIncomeMethod)
                            .addComponent(comboBoxIncomeMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonIncomeCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIncomeSource)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxIncomeSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePickerIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelIncomeMethod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxIncomeMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelIncomeAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerIncomeSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxIncomeComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIncomeCancel)
                    .addComponent(buttonAddIncome))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIncomeCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncomeCancelActionPerformed
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_buttonIncomeCancelActionPerformed

    private void buttonAddIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddIncomeActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        if (evt.getSource() instanceof JButton) {
            if (getComboBoxIncomeSource().getSelectedIndex() == 0) {
                getLabelIncomeSource().setForeground(Color.RED);
                flag = true;
            }
            if (getComboBoxIncomeMethod().getSelectedIndex() == 0) {
                getLabelIncomeMethod().setForeground(Color.RED);
                flag = true;
            }
            if (Double.parseDouble(getSpinnerIncomeSum().getValue().toString()) == 0) {
                getLabelIncomeAmount().setForeground(Color.RED);
                flag = true;
            }
            if (flag) {
                JOptionPane.showConfirmDialog(this, "אנא מלאו את כל השדות הנצרכות", "Cashew", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (getIncomeDescription().trim().equals("")) {
                setIncomeDescription(getIncomeSource());
            }
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            SimpleDateFormat sdf = new SimpleDateFormat("_ddMMyyyy");
            TransactionParser.addTransactionRoutine(new Income(sdf.format(getDate().getTime()) + "I", getAmount(), getDate(), getIncomeDescription(), getIncomeMethod(), getIncomeSource(), getIconPath()));

            TransactionParser.transactionChangesRoutine();
        }
    }//GEN-LAST:event_buttonAddIncomeActionPerformed

    private void comboBoxIncomeMethodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxIncomeMethodItemStateChanged
        // TODO add your handling code here:
        if (getLabelIncomeMethod().getForeground() == Color.RED) {
            getLabelIncomeMethod().setForeground(Color.BLACK);
        }
        if (evt.getSource() instanceof JComboBox) {
            setIncomeMethod(((JComboBox) evt.getSource()).getSelectedItem().toString());
        }
    }//GEN-LAST:event_comboBoxIncomeMethodItemStateChanged

    private void comboBoxIncomeSourceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxIncomeSourceItemStateChanged
        // TODO add your handling code here:
        if (getLabelIncomeSource().getForeground() == Color.RED) {
            getLabelIncomeSource().setForeground(Color.BLACK);
        }
        if (evt.getSource() instanceof JComboBox) {
            setIconPath("images/" + TransactionParser.INCOME_ICON_ARR[((JComboBox) evt.getSource()).getSelectedIndex()]);
            setIncomeSource(((JComboBox) evt.getSource()).getSelectedItem().toString());
//            System.out.println(iconName);
//            System.out.println(catagory);
        }
    }//GEN-LAST:event_comboBoxIncomeSourceItemStateChanged

    private void datePickerIncomePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerIncomePropertyChange
        // TODO add your handling code here:
        if (evt.getSource() instanceof JXDatePicker) {
            setDate(new GregorianCalendar());
            getDate().setTime(((JXDatePicker) evt.getSource()).getDate());
            //System.out.println(date);
        }
    }//GEN-LAST:event_datePickerIncomePropertyChange

    private void spinnerIncomeSumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerIncomeSumStateChanged
        // TODO add your handling code here:
        if (getLabelIncomeAmount().getForeground() == Color.RED) {
            getLabelIncomeAmount().setForeground(Color.BLACK);
        }
        if (evt.getSource() instanceof JSpinner) {
            setAmount(Double.parseDouble(((JSpinner) evt.getSource()).getValue().toString()));
            //System.out.println(amount);
        }
    }//GEN-LAST:event_spinnerIncomeSumStateChanged

    private void spinnerIncomeSumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinnerIncomeSumFocusLost
        // TODO add your handling code here:
        if (evt.getSource() instanceof JSpinner) {
            setAmount(Double.parseDouble(((JSpinner) evt.getSource()).getValue().toString()));
            //System.out.println(amount);
        }
    }//GEN-LAST:event_spinnerIncomeSumFocusLost

    private void textBoxIncomeCommentsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBoxIncomeCommentsKeyReleased
        // TODO add your handling code here:
        if (evt.getSource() instanceof JTextField) {
            setIncomeDescription(((JTextField) evt.getSource()).getText() != null ? ((JTextField) evt.getSource()).getText() : "");
            //System.out.println(incomeDescription);
        }
    }//GEN-LAST:event_textBoxIncomeCommentsKeyReleased

    private void textBoxIncomeCommentsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBoxIncomeCommentsKeyTyped
        // TODO add your handling code here:
        if ((evt.getSource() instanceof JTextField) && (((JTextField) evt.getSource()).getText().length() >= 22)) {
            evt.consume();
        }
    }//GEN-LAST:event_textBoxIncomeCommentsKeyTyped

    private void jPanel1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorRemoved

        MainWindow.getProgram().getButtonNewExpense().setEnabled(true);
        MainWindow.getProgram().getButtonNewIncome().setEnabled(true);
        MainWindow.getProgram().getButtonNewExpense1().setEnabled(true);
        MainWindow.getProgram().getButtonNewIncome1().setEnabled(true);
    }//GEN-LAST:event_jPanel1AncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewIncome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddIncome;
    private javax.swing.JButton buttonIncomeCancel;
    private javax.swing.JComboBox<String> comboBoxIncomeMethod;
    private javax.swing.JComboBox<String> comboBoxIncomeSource;
    private org.jdesktop.swingx.JXDatePicker datePickerIncome;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelIncomeAmount;
    private javax.swing.JLabel labelIncomeMethod;
    private javax.swing.JLabel labelIncomeSource;
    private javax.swing.JSpinner spinnerIncomeSum;
    private javax.swing.JTextField textBoxIncomeComments;
    // End of variables declaration//GEN-END:variables

    private String incomeMethod;
    private String incomeSource;
    private String incomeDescription;
    private String iconPath;
    private double amount;
    private Calendar date;

    public JComboBox<String> getComboBoxIncomeMethod() {
        return comboBoxIncomeMethod;
    }

    public void setComboBoxIncomeMethod(JComboBox<String> comboBoxIncomeMethod) {
        this.comboBoxIncomeMethod = comboBoxIncomeMethod;
    }

    public JComboBox<String> getComboBoxIncomeSource() {
        return comboBoxIncomeSource;
    }

    public void setComboBoxIncomeSource(JComboBox<String> comboBoxIncomeSource) {
        this.comboBoxIncomeSource = comboBoxIncomeSource;
    }

    public JLabel getLabelIncomeMethod() {
        return labelIncomeMethod;
    }

    public void setLabelIncomeMethod(JLabel labelIncomeMethod) {
        this.labelIncomeMethod = labelIncomeMethod;
    }

    public JLabel getLabelIncomeAmount() {
        return labelIncomeAmount;
    }

    public void setLabelIncomeAmount(JLabel labelIncomeAmount) {
        this.labelIncomeAmount = labelIncomeAmount;
    }

    public JLabel getLabelIncomeSource() {
        return labelIncomeSource;
    }

    public void setLabelIncomeSource(JLabel labelIncomeSource) {
        this.labelIncomeSource = labelIncomeSource;
    }

    public JSpinner getSpinnerIncomeSum() {
        return spinnerIncomeSum;
    }

    public void setSpinnerIncomeSum(JSpinner spinnerIncomeSum) {
        this.spinnerIncomeSum = spinnerIncomeSum;
    }

    public JTextField getTextBoxIncomeComments() {
        return textBoxIncomeComments;
    }

    public void setTextBoxIncomeComments(JTextField textBoxIncomeComments) {
        this.textBoxIncomeComments = textBoxIncomeComments;
    }

    public String getIncomeMethod() {
        return incomeMethod;
    }

    public void setIncomeMethod(String incomeMethod) {
        this.incomeMethod = incomeMethod;
    }

    public String getIncomeSource() {
        return incomeSource;
    }

    public void setIncomeSource(String incomeSource) {
        this.incomeSource = incomeSource;
    }

    public String getIncomeDescription() {
        return incomeDescription;
    }

    public void setIncomeDescription(String incomeDescription) {
        this.incomeDescription = incomeDescription;
    }

    public String getIconPath() {
        return iconPath;
    }

    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Calendar getDate() {
        return date;
    }

    public void setDate(Calendar date) {
        this.date = date;
    }

}
